const express = require("express");
const { ethers } = require("ethers");

const app = express();
const PORT = process.env.PORT || 3004;

const NAME = "Report Agent";
const VERSION = "1.0.0";

const processedJobs = new Set();

app.use(express.json());

function buildReport({ topic, keywords, sentiment, score }) {
  const sentimentLabel =
    sentiment === "positive" ? "Positive" : sentiment === "negative" ? "Negative" : "Neutral";
  const sentimentEmoji =
    sentiment === "positive" ? "↑" : sentiment === "negative" ? "↓" : "→";

  const keywordList = (keywords || []).map((k) => `• ${k}`).join("\n");
  const date = new Date().toISOString().split("T")[0];

  return [
    `# Research Report${topic ? `: ${topic}` : ""}`,
    `Generated: ${date}`,
    "",
    "## Summary",
    `Overall sentiment for this topic is **${sentimentLabel}** ${sentimentEmoji} (score: ${score}).`,
    "",
    "## Key Topics Identified",
    keywordList || "• No significant keywords found",
    "",
    "## Analysis",
    sentiment === "positive"
      ? "The content reflects strong positive developments and growth indicators in this area. Key themes suggest continued momentum and adoption."
      : sentiment === "negative"
      ? "The content highlights challenges and risk factors in this area. Caution is advised and further monitoring recommended."
      : "The content presents a balanced view with both opportunities and challenges noted. The area appears stable with moderate development activity.",
    "",
    "---",
    `Report generated by ${NAME} v${VERSION} via MilkyWay Protocol`,
  ].join("\n");
}

app.get("/health", (_req, res) => {
  res.json({ name: NAME, version: VERSION, status: "ok" });
});

app.get("/about", (_req, res) => {
  res.json({
    milkyway_version: "1.0",
    name: NAME,
    description: "Formats analysis results into a human-readable markdown report. Designed to chain after Analyze Agent.",
    capabilities: ["report", "format", "summarize"],
    pricing: { model: "per_job", amount: "0.0001", currency: "ETH" },
    input_schema: {
      keywords: { type: "array", required: true, description: "Keywords from analysis" },
      sentiment: { type: "string", required: true, description: "Sentiment from analysis" },
      score: { type: "number", required: true, description: "Sentiment score" },
      topic: { type: "string", required: false, description: "Original topic" },
    },
    output_schema: {
      report: { type: "string", description: "Formatted markdown report" },
      timestamp: { type: "number", description: "Unix timestamp of report generation" },
      topic: { type: "string", description: "Topic covered in the report" },
    },
    max_deadline_seconds: 10,
  });
});

app.post("/execute", async (req, res) => {
  const { milkyway_version, job_id, escrow_tx, task, deadline } = req.body;

  if (milkyway_version !== "1.0") {
    return res.status(400).json({ error: "Unsupported protocol version" });
  }

  if (deadline < Math.floor(Date.now() / 1000)) {
    return res.status(408).json({
      milkyway_version: "1.0", job_id, status: "expired",
      error: "Deadline has passed",
    });
  }

  if (processedJobs.has(job_id)) {
    return res.status(409).json({
      milkyway_version: "1.0", job_id, status: "duplicate",
      error: "Job already processed",
    });
  }

  const valid = await verifyEscrow(escrow_tx, job_id);
  if (!valid) {
    return res.status(402).json({
      milkyway_version: "1.0", job_id, status: "payment_required",
      error: "Escrow not verified",
    });
  }

  processedJobs.add(job_id);

  const { keywords, sentiment, score, topic } = task.input;
  const report = buildReport({ topic, keywords, sentiment, score });
  const timestamp = Math.floor(Date.now() / 1000);

  res.json({
    milkyway_version: "1.0",
    job_id,
    status: "completed",
    output: { report, timestamp, topic: topic || null },
    completed_at: timestamp,
  });
});

const ESCROW_ABI = [
  "function getJob(bytes32 jobId) external view returns (tuple(bytes32,address,address[],uint256[],uint256,uint256,uint8,uint256,uint256))",
];

async function verifyEscrow(_escrowTx, jobId) {
  try {
    const rpc = process.env.ARBITRUM_RPC || "https://arb-sepolia.g.alchemy.com/v2/Ukyp1Ogy1qih7QQ6fO8FY";
    const escrowAddress = process.env.JOB_ESCROW_ADDRESS || "0xdefea667504b720972cdc723124796a03756d384";
    const provider = new ethers.JsonRpcProvider(rpc);
    const contract = new ethers.Contract(escrowAddress, ESCROW_ABI, provider);
    const job = await contract.getJob(jobId);
    return job[6] === 1n || job[6] === 0n;
  } catch {
    return false;
  }
}

app.listen(PORT, () => {
  console.log(`${NAME} v${VERSION} running on http://localhost:${PORT}`);
  console.log(`  Health:  GET  /health`);
  console.log(`  About:   GET  /about`);
  console.log(`  Execute: POST /execute`);
});
