FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma/ ./prisma/

RUN npm install

COPY tsconfig.json ./
COPY src/ ./src/

RUN npx prisma generate
RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", "dist/index.js"]
